name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: ConfigureGit
      run: git config --global url."https://github.com/".insteadOf git@github.com
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
